### PR TITLE
Py35

### PR DESCRIPTION
**Pull request by edouardruiz**
Trying to make ezbbg_ws compatible with python 3.5.

### CODE REVIEW

**Comment by garaud** [comment]
Hi,
Very interesting! Thanks a lot. I will be in the first py3 users.
Cheers,
Damien

**Comment by edouardruiz** [comment]
Hi,

Happy to hear that, but I guess you miss a Bloomberg terminal. Come back to SG ! ;)

Cheers,

-- 
Edouard Ruiz
+33 6 84 22 13 29

**Comment by garaud** [comment]
*oops* I thought this GH notification dealed with ezhc. Of course I cannot use this Web Service wo a Bloom terminal...
Sorry ;-p

**Comment by oscar6echo** [comment]
But now if you have a look at ezhc & ezvis3d it's Python3 compatible.

**Pull request merged**
